# Generated by Django 5.2 on 2025-04-28 12:23

import books.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('F', 'Fiction'), ('NF', 'Non-Fiction'), ('FA', 'Fantasy'), ('FA', 'Fantasy'), ('SF', 'Sci-fi'), ('TH', 'Thriller'), ('R', 'Romance'), ('BI', 'Biography'), ('H', 'History'), ('SH', 'Self_help')], max_length=2)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to=books.models.get_upload_to)),
                ('borrowed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Book',
                'db_table': 'books_table',
                'ordering': ['BID'],
            },
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'verbose_name': 'Borrow',
                'db_table': 'borrowed_books_table',
                'ordering': ['borrowed_at'],
            },
        ),
    ]
