# Generated by Django 5.2 on 2025-04-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('F', 'Fiction'), ('NF', 'Non-Fiction'), ('FA', 'Fantasy'), ('MY', 'Mystrey'), ('SF', 'Sci-fi'), ('TH', 'Thriller'), ('R', 'Romance'), ('BI', 'Biography'), ('H', 'History'), ('SH', 'Self_help')], max_length=2),
        ),
    ]
