# Generated by Django 5.2 on 2025-04-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='duration',
            field=models.CharField(choices=[('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('2_months', '2 Months')], default='1 Week', max_length=10),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('FI', 'Fiction'), ('NO', 'Non-Fiction'), ('FA', 'Fantasy'), ('MY', 'Mystrey'), ('SC', 'Sci-fi'), ('TH', 'Thriller'), ('RO', 'Romance'), ('BI', 'Biography'), ('HI', 'History'), ('SE', 'Self_help')], max_length=2),
        ),
    ]
