# Generated by Django 5.2 on 2025-04-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrowedbook_duration_borrowedbook_returned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='fullname',
            field=models.TextField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='returned',
            field=models.BooleanField(default=True),
        ),
    ]
