# Generated by Django 5.2 on 2025-04-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrowedbook_fullname_alter_borrowedbook_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
